server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/edge.p12
    key-store-password: '{cipher}8d2340da9b72c54276b6347217767e60eabe8f027a6c7ece3cb1704b64c28d67'
    key-alias: localhost
  error:
    include-message: always

# We will get these from the discovery server
app: # We are using service discovery
  product-service:
    url: http://product-service
  recommendation-service:
    url: http://recommendation-service
  review-service:
    url: http://review-service
  composite-service:
    url: http://product-composite-service
  auth-server:
    url: http://auth-server

spring:
  # OAuth2 Resource security

  # Using the local auth-server in the project
  security.oauth2.resourceserver.jwt.jwk-set-uri: http://${service.auth-server.host}:${service.auth-server.port}/.well-known/jwks.json

  # Using the OAuth2 provider domain - Auth0
  #security.oauth2.resourceserver.jwt.issuer-uri: https://dev-habeebcycle-m1.auth0.com/

  # Cloud gateway routes settings
  cloud:
    gateway:
      #httpclient:
      #connect-timeout: 20000
      #response-timeout: 20s
      routes:
        - id: product-composite
          uri: lb://product-composite-service
          predicates:
            - Path=/product-composite/**
        - id: oauth-server
          uri: lb://auth-server
          predicates:
            - Path=/oauth/**
        - id: discovery-server-api
          uri: http://${service.discovery-server.host}:${service.discovery-server.port}
          predicates:
            - Path=/eureka/api/{segment}
          filters:
            - SetPath=/eureka/{segment}
        - id: discovery-server-web
          uri: http://${service.discovery-server.host}:${service.discovery-server.port}
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-other
          uri: http://${service.discovery-server.host}:${service.discovery-server.port}
          predicates:
            - Path=/eureka/**
        - id: config-server
          uri: http://${service.config-server.host}:${service.config-server.port}
          predicates:
            - Path=/config/**
          filters:
            - RewritePath=/config/(?<segment>.*), /$\{segment}

        # Testing some routes
        - id: host_route_200
          uri: http://httpstat.us
          predicates:
            - Host=i.feel.lucky:8080
            - Path=/headerrouting/**
          filters:
            - SetPath=/200
        - id: host_route_418
          uri: http://httpstat.us
          predicates:
            - Host=im.a.teapot:8080
            - Path=/headerrouting/**
          filters:
            - SetPath=/418
        - id: host_route_501
          uri: http://httpstat.us
          predicates:
            - Path=/headerrouting/**
          filters:
            - SetPath=/501

# Logging settings
logging:
  level:
    root: INFO
    com.habeebcycle: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE