spring:
  application:
    name: discovery-server

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistery: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  # https://github.com/spring-cloud-samples/eureka/blob/master/src/main/resources/application.yml
  server:
    waitTimeInMsWhenSyncEmpty: 0
    response-cache-update-interval-ms: 5000

# Actuator endpoints
management.endpoints.web.exposure.include: "*"

---
spring:
  config:
    activate:
      on-profile:
        - kubernetes

#Enable liveness and readiness probes
management.health.probes.enabled: true