server:
  port: 7003
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost/review-db
    username: user
    password: pwd
    hikari.initializationFailTimeout: 60000
  # Strongly recommended to set this property to "none" in production environment!
  jpa.hibernate.ddl-auto: update

logging:
  level:
    root: INFO
    com.habeebcycle: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring:
  config:
    activate:
      on-profile:
        - docker
  datasource:
    url: jdbc:mysql://mysql/review-db

server:
  port: 8080