spring:
  application:
    name: auth-server

  # Config sever configurations
  config.import: optional:configserver:http://localhost:8888
  cloud.config:
    username: ${CONFIG_SERVER_USER}
    password: ${CONFIG_SERVER_PWD}
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    #uri: http://${CONFIG_SERVER_USER}:${CONFIG_SERVER_PWD}@${service.config-server.host}:${service.config-server.port}

---
spring:
  config:
    activate:
      on-profile:
        - docker
    import: optional:configserver:http://config-server:8888

---
spring:
  config:
    activate:
      on-profile:
        - kubernetes
    import: optional:configserver:http://config-server:8888